Repository DentiioApp/dentiio-api, pull requests merged in 2020-09, with the labels that each got.

#55 Add the swiftmailer
  api/composer.json
  api/composer.lock
  api/config/bundles.php
  api/config/packages/dev/swiftmailer.yaml
  api/config/packages/swiftmailer.yaml
  api/config/packages/test/swiftmailer.yaml
  api/phpunit.xml.dist
  api/symfony.lock
Labels: toMerge

#60 Lory rewind user job structure
  api/src/DataFixtures/AppFixtures.php
  api/src/Entity/Commentaire.php
  api/src/Entity/Keyword.php
  api/src/Entity/User.php
Labels: bug, toMerge

#63 add name to roups missed
  api/src/Entity/Pathologie.php
  api/src/Entity/Speciality.php
  api/src/Entity/Symptome.php
  api/src/Entity/Treatment.php
Labels: toMerge

#64 Features link job clinicalcase
  api/src/Entity/ImageClinicalCase.php
  api/src/Entity/ImageClinicalCaseType.php
  api/src/Entity/Jobs.php
Labels: toMerge

#68 Fixtures image
  api/src/DataFixtures/AppFixtures.php
  api/src/Entity/ImageClinicalCase.php
  api/src/Events/ConvertBase64ToImage.php
Labels: toMerge

#70 Features JWT
  api/config/services.yaml
  api/public/index.php
  api/src/Events/JWTCreatedSubscriber.php
Labels: toMerge

#72 update the clinical case entity
  api/src/DataFixtures/AppFixtures.php
  api/src/Entity/ClinicalCase.php
Labels: toMerge

#74 Fix the docker bug
  api/composer.lock
  api/config/packages/doctrine_migrations.yaml
  api/symfony.lock
  docker/php.Dockerfile
Labels: bug
