Repository DentiioApp/dentiio-api, pull requests merged in 2021-01, with the labels that each got.

#93 Feature composer version and mariaDB version
  .dockerignore
  README.md
  docker-compose.yml
  docker/php.Dockerfile
Labels: Correction, bug, toMerge

#95 toMerge
  api/src/Entity/ClinicalCaseOmnipratique.php
  api/src/Entity/Commentaire.php
  api/src/Entity/Favorite.php
  api/src/Entity/ImageClinicalCaseType.php
  api/src/Entity/ImgClinicalCaseOmnipratique.php
  api/src/Entity/Notation.php
  api/src/Entity/Patient.php
  api/src/Entity/Speciality.php
  api/src/Entity/User.php
  api/src/Repository/ClinicalCaseOmnipratiqueRepository.php
  api/src/Repository/CommentRepository.php
  api/src/Repository/ImgClinicalCaseOmnipratiqueRepository.php
Labels: toMerge

#98 route api clinical case omno
  api/src/Entity/ImgClinicalCaseOmnipratique.php
Labels: Correction, enhancement
